### ISSUE TITLE
TideWalletJs init db with path

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/CryptoWolf#16]
- remove singleton
- check db construct
- init with path like /hash(installId+thirdPartyId)/tidewalletJs.db

**Comment by Waiting4Ever** [comment]
https://github.com/BOLT-Protocol/TideWalletJS/pull/76

**Comment by Luphia** [comment]
- remain testing
- remain 1 hr (used 3 hrs)

**Comment by Luphia** [comment]
used 4 hrs
