### ISSUE TITLE
ask coinMarketCap price

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/CryptoWolf#18]
- use Tidewallet-Backend
- request per 20 mins
- change backend production, staging, temp staging env api key
- change staging sync Ropsten using infura
- change TideWalletJs getFialList interval

**Comment by Waiting4Ever** [comment]
https://github.com/BOLT-Protocol/TideWallet-Backend/pull/162

**Comment by Luphia** [comment]
remain < 1 hr (used 1 hr)

**Comment by Luphia** [comment]
used 2 hrs
