### ISSUE TITLE
ask backend price and keep the pair price at the same value

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/CryptoWolf#19]

**Comment by Luphia** [comment]
- Pair A - B
- Liquidity A = La, B = Lb
- Price Pa = Lb / La
- Price Pb = La / Lb
- Traget Price TPa

# Case 1 : TPa > Pa, TPb < Pb
TPa = xPa (x > 1)
-> use n B to buy A
-> n = (sqrt(x) - 1) * Lb

# Case 2 : TPa < Pa, TPb > Pb
TPb = xPb
-> use n A to buy B
-> n = (sqrt(x) - 1) * La

**Comment by Waiting4Ever** [comment]
TideWalletJs
https://github.com/BOLT-Protocol/TideWalletJS/pull/77

**Comment by Luphia** [comment]
remain 2hrs (used 1.5 hr)

**Comment by Luphia** [comment]
used 7.5 hrs
