### ISSUE TITLE
backend, crawler and parser enhancement

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/CryptoWolf#21]
- addressTransaction table add constraint
- findorCreate change to create
- fail error handle

**Comment by Luphia** [comment]
remain 2 hrs (used 3 hrs)

**Comment by Luphia** [comment]
used 5 hrs

**Comment by Luphia** [comment]
crawler: https://github.com/BOLT-Protocol/TideWallet-Backend-Crawler/pull/5
parser: https://github.com/BOLT-Protocol/TideWallet-Backend-Parser/pull/25
