### ISSUE TITLE
Trade every 15 seconds

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/CryptoWolf#5]
Trade every 15 seconds, if eP > mP => Buy A, if eP < mP => Buy B

**Comment by Luphia** [comment]
- get pair by token address
- get token detail
- get price
- get simulative trading amount
- approve
- swap

**Comment by Luphia** [comment]
remain 2 hrs (used 1.5 hr)

**Comment by Luphia** [comment]
used 6.5 hrs (not yet)

**Comment by Luphia** [comment]
used 7.5 hrs
